server:
  port: 9502

logging:
  level:
    root: info
    com.knox.template: debug

spring:
  application:
    name: template-search
  datasource:
    url: jdbc:mysql://localhost:3306/template-alibaba?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  # cloud
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080

mybatis-plus:
  type-aliases-package: com.knox.template.commons.domain
  mapper-locations: classpath*:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"